### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by dschniepp** [SmoothPhp/CQRS-ES-Framework-Laravel#12]
The project looks pretty promising, do you have any plans on writing a **how to**?

Cheers

**Comment by mrsimonbennett** [comment]
Hello @dschniepp I do have some screencasts if you are interested . And started writing the wiki on the main project to https://github.com/SmoothPhp/CQRS-ES-Framework/wiki

**Comment by dschniepp** [comment]
Thank you. You are talking about https://www.youtube.com/watch?v=OA8Hj_XwFQU and https://www.youtube.com/watch?v=cG4JSMyNc0Y? Do you have an example project, where I can take a look at the implementation?

**Comment by mrsimonbennett** [comment]
Yeah they are the ones. There are two less popular videos on the SmoothPhp channel https://www.youtube.com/channel/UCv1y0zTtEWv65gDyKiUg8Iw

I have just opened sourced a dead project I ES with a friend https://github.com/mrsimonbennett/core feel free to have a look about

**Comment by dschniepp** [comment]
Awesome, thank you very much!

**Comment by mrsimonbennett** [comment]
any questions just ask
